# Conda Environment Configuration for NeoMate AI
# ===============================================
# This environment.yml file provides a Conda-based setup alternative to pip,
# particularly beneficial for users requiring system-level dependencies like
# OpenCV, Tesseract, and FFmpeg. It ensures cross-platform compatibility and
# simplifies installation on systems with Conda/Miniconda installed.

name: neomate-ai-env

channels:
  - conda-forge # Primary channel for community-maintained packages
  - defaults # Anaconda's default channel for stability

dependencies:
  # Core Python environment
  - python=3.10

  # System-level dependencies available via Conda
  - pip
  - numpy>=1.21.0 # Numerical computing library
  - scipy>=1.7.0 # Scientific computing library
  - opencv>=4.5.0 # Computer vision library
  - tesseract>=5.0.0 # OCR engine
  - ffmpeg>=4.3 # Multimedia framework for audio/video processing
  - zlib # Compression library
  - libpng # PNG image library
  - libjpeg-turbo # JPEG image library

  # Pip-managed packages (for packages not available or preferred via pip)
  - pip:
      - poetry>=1.5.0 # Python dependency management tool
      # Additional pip packages can be added here as the project evolves
      # Ensure compatibility with Conda-installed packages to avoid conflicts
